-- ============================================================
-- Fresh & Pure (Dinesh Farms) — Customer API Schema (PostgreSQL)
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gen_random_uuid()

-- ---------- Users ----------
CREATE TABLE users (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone               TEXT NOT NULL UNIQUE,
  first_name          TEXT,
  last_name           TEXT,
  email               TEXT,
  dob                 DATE,
  profile_completed   BOOLEAN NOT NULL DEFAULT false,
  default_address_id  UUID,
  device_tokens       TEXT[] NOT NULL DEFAULT '{}',   -- FCM tokens for push notifications
  refresh_token_hash  TEXT,
  active              BOOLEAN NOT NULL DEFAULT true,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- OTP verification ----------
CREATE TABLE otp_verifications (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone       TEXT NOT NULL,
  otp_hash    TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  attempts    INTEGER NOT NULL DEFAULT 0,
  verified    BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_otp_phone ON otp_verifications (phone, created_at DESC);
-- Expired rows are cleaned up by a small periodic DELETE (see utils/otpService.js) —
-- Postgres has no built-in TTL index like Mongo, so this is done explicitly.

-- ---------- Addresses ----------
CREATE TABLE addresses (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  residence_type         TEXT NOT NULL CHECK (residence_type IN ('COMMUNITY_APARTMENT','INDEPENDENT')),
  flat_no_apartment_floor TEXT NOT NULL,
  block_tower            TEXT,
  pincode                TEXT NOT NULL,
  landmark               TEXT,
  lat                    DOUBLE PRECISION NOT NULL,
  lng                    DOUBLE PRECISION NOT NULL,
  delivery_instructions  TEXT[] NOT NULL DEFAULT '{}',  -- subset of PET_AT_HOME, LEAVE_AT_DOOR, RING_BELL, PLACE_IN_BAG, AT_SHOE_RACK, AT_SECURITY
  is_default             BOOLEAN NOT NULL DEFAULT false,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_addresses_user ON addresses (user_id);

ALTER TABLE users
  ADD CONSTRAINT fk_users_default_address FOREIGN KEY (default_address_id) REFERENCES addresses(id);

-- ---------- Products ----------
CREATE TABLE products (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name           TEXT NOT NULL,
  slug           TEXT NOT NULL UNIQUE,          -- "a2-buffalo-milk" — drives the order-ID abbreviation
  category       TEXT NOT NULL CHECK (category IN ('CURD','PANEER','GHEE','BUTTER','MILK','NON_DAIRY')),
  quantity_label TEXT NOT NULL,                 -- "500 ml"
  tags           TEXT[] NOT NULL DEFAULT '{}',  -- ["A2 Protein","Rich & Creamy"]
  description    TEXT,
  nutrition      JSONB,                          -- { proteinG, sodiumMg, calciumMg, energyKcal, totalFatG, carbohydrateG }
  quality_badges TEXT[] NOT NULL DEFAULT '{}',  -- ["Lab Tested","No Additives","Farm Fresh"]
  images         TEXT[] NOT NULL DEFAULT '{}',
  price          NUMERIC(10,2) NOT NULL,
  mrp            NUMERIC(10,2) NOT NULL,
  active         BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  main_img_nobg TEXT NOT NULL
);

CREATE TABLE category_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL UNIQUE,
  image_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO category_types (type, image_url) VALUES
  (
    'All',
    'https://fsqavgaecpxcgdwtvgsd.supabase.co/storage/v1/object/sign/products/all.png?token=eyJraWQiOiI5YTdlZmUyMy1iMWIyLTRmMDAtOGVjMi1kZDFkYzFmZWZiMzEiLCJhbGciOiJIUzUxMiJ9.eyJ1cmwiOiJwcm9kdWN0cy9hbGwucG5nIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc5MTIyMDIzMiwiZXhwIjoxODIyNzU2MjMyfQ.PZZDR6aiGoelH2LY8rcdYbFr6N-qJ_xqLXMjTqiQS_G4PaPoXLPHryXlyyVw5p55cKIld1MyjbMBPqx2YwcCBQ'
  ),
  (
    'Milk',
    'https://fsqavgaecpxcgdwtvgsd.supabase.co/storage/v1/object/sign/products/A2BufalloMilk-removebg-preview.png?token=eyJraWQiOiI5YTdlZmUyMy1iMWIyLTRmMDAtOGVjMi1kZDFkYzFmZWZiMzEiLCJhbGciOiJIUzUxMiJ9.eyJ1cmwiOiJwcm9kdWN0cy9BMkJ1ZmFsbG9NaWxrLXJlbW92ZWJnLXByZXZpZXcucG5nIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc5MTIyMDI2MSwiZXhwIjoxODIyNzU2MjYxfQ.xTJRxp2BIlOmnd7m-mL32bppHB8u_nur_8D3iBYA1fesqWWmA-dBlMUW8tCpcTHepoPHat80QWVztHD48ZKt1Q'
  ),
  (
    'Curd',
    'https://fsqavgaecpxcgdwtvgsd.supabase.co/storage/v1/object/sign/products/CowCurd-removebg-preview.png?token=eyJraWQiOiI5YTdlZmUyMy1iMWIyLTRmMDAtOGVjMi1kZDFkYzFmZWZiMzEiLCJhbGciOiJIUzUxMiJ9.eyJ1cmwiOiJwcm9kdWN0cy9Db3dDdXJkLXJlbW92ZWJnLXByZXZpZXcucG5nIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc5MTIyMDMxNSwiZXhwIjoxODIyNzU2MzE1fQ.saNnboxRvB2DlwmSiZm_22O_G6_bd3-TpHlubPVwxn-pMvXuf1_2oJ0K6MQ_As9zHmB55vsrElRsg89nMePNCg'
  ),
  (
    'Paneer',
    'https://fsqavgaecpxcgdwtvgsd.supabase.co/storage/v1/object/sign/products/malaipanner-removebg-preview.png?token=eyJraWQiOiI5YTdlZmUyMy1iMWIyLTRmMDAtOGVjMi1kZDFkYzFmZWZiMzEiLCJhbGciOiJIUzUxMiJ9.eyJ1cmwiOiJwcm9kdWN0cy9tYWxhaXBhbm5lci1yZW1vdmViZy1wcmV2aWV3LnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3OTEyMjAzMzIsImV4cCI6MTgyMjc1NjMzMn0.HKbJycXlgZ5uSoYDmSBkPSLqu51-iRk1zJMDV2kNbFJNQbNya5XS8ppyN2JGbYv4iAFqpKm41SuJHrwbJK0OZg'
  ),
  (
    'Ghee',
    'https://fsqavgaecpxcgdwtvgsd.supabase.co/storage/v1/object/sign/products/buffaloghee-removebg-preview.png?token=eyJraWQiOiI5YTdlZmUyMy1iMWIyLTRmMDAtOGVjMi1kZDFkYzFmZWZiMzEiLCJhbGciOiJIUzUxMiJ9.eyJ1cmwiOiJwcm9kdWN0cy9idWZmYWxvZ2hlZS1yZW1vdmViZy1wcmV2aWV3LnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3OTEyMjAzNTIsImV4cCI6MTgyMjc1NjM1Mn0.h3jbwXI6_Yl_LbSr6hkMbj3Vdn_DqD0yRPh93c3UEhE51zYN7IgTserephmWhKOSCDo234Siz9loCcHEHuu-dg'
  ),
  (
    'Butter',
    'https://fsqavgaecpxcgdwtvgsd.supabase.co/storage/v1/object/sign/products/buffalobutter-removebg-preview.png?token=eyJraWQiOiI5YTdlZmUyMy1iMWIyLTRmMDAtOGVjMi1kZDFkYzFmZWZiMzEiLCJhbGciOiJIUzUxMiJ9.eyJ1cmwiOiJwcm9kdWN0cy9idWZmYWxvYnV0dGVyLXJlbW92ZWJnLXByZXZpZXcucG5nIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc5MTIyMDQzOCwiZXhwIjoxODIyNzU2NDM4fQ.LJ6e0IAQL849E8CglqqPJgQLtcwsuusAJxfddn17o0KFmEaTEdVMVvQZsaBh6_2BiOKSJduQaq0Bgcp4BC2YTA'
  ),
  (
    'Dairy',
    'https://fsqavgaecpxcgdwtvgsd.supabase.co/storage/v1/object/sign/products/A2BufalloMilk-removebg-preview.png?token=eyJraWQiOiI5YTdlZmUyMy1iMWIyLTRmMDAtOGVjMi1kZDFkYzFmZWZiMzEiLCJhbGciOiJIUzUxMiJ9.eyJ1cmwiOiJwcm9kdWN0cy9BMkJ1ZmFsbG9NaWxrLXJlbW92ZWJnLXByZXZpZXcucG5nIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc5MTIyMDQ3OSwiZXhwIjoxODIyNzU2NDc5fQ.Cox5Y51GYMgqKVunEKOWYbTITkV8KOkLaSuYRHtmj6CgtQySw7RaSz1SG9cWsM6qjR64dUurmsa3C1gB9pKhpQ'
  ),
  (
    'Non Dairy',
    'https://fsqavgaecpxcgdwtvgsd.supabase.co/storage/v1/object/sign/products/honey-removebg-preview.png?token=eyJraWQiOiI5YTdlZmUyMy1iMWIyLTRmMDAtOGVjMi1kZDFkYzFmZWZiMzEiLCJhbGciOiJIUzUxMiJ9.eyJ1cmwiOiJwcm9kdWN0cy9ob25leS1yZW1vdmViZy1wcmV2aWV3LnBuZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3OTEyMjExNjMsImV4cCI6MTgyMjc1NzE2M30.90EskF0ajWUM7iOn8l2SC_-RZAXWlHtuS5_OwlvIoAKnl4TyKJySWEcv4m5h_AY_cf14ZXWdkDuyTXESti3mvA'
  )
ON CONFLICT (type) DO UPDATE SET image_url = EXCLUDED.image_url;

-- ---------- Order ID counters (atomic, daily-per-product) ----------
CREATE TABLE order_counters (
  counter_key TEXT PRIMARY KEY,   -- e.g. "CM20260912"
  seq         INTEGER NOT NULL DEFAULT 0
);

-- ---------- Orders (buy-once) ----------
CREATE TABLE orders (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id              TEXT NOT NULL UNIQUE,   -- "DF-CM20260912-098"
  user_id               UUID NOT NULL REFERENCES users(id),
  address_id            UUID NOT NULL REFERENCES addresses(id),
  product_id            UUID NOT NULL REFERENCES products(id),
  quantity              INTEGER NOT NULL DEFAULT 1,
  delivery_date         DATE NOT NULL,
  slot                  TEXT NOT NULL CHECK (slot IN ('MORNING','EVENING')),
  price_at_order        NUMERIC(10,2) NOT NULL,   -- snapshot, protects invoices from later price changes
  total_amount          NUMERIC(10,2) NOT NULL,
  status                TEXT NOT NULL DEFAULT 'SCHEDULED'
                          CHECK (status IN ('SCHEDULED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')),
  wallet_transaction_id UUID,
  source                TEXT NOT NULL DEFAULT 'ONE_TIME' CHECK (source IN ('ONE_TIME','SUBSCRIPTION')),
  subscription_id       UUID,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_orders_user_date ON orders (user_id, delivery_date DESC);

CREATE UNIQUE INDEX uq_orders_subscription_date_slot
  ON orders (subscription_id, delivery_date, slot)
  WHERE subscription_id IS NOT NULL;

-- ---------- Subscriptions (all three frequency types) ----------
CREATE TABLE subscriptions (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID NOT NULL REFERENCES users(id),
  address_id        UUID NOT NULL REFERENCES addresses(id),
  product_id        UUID NOT NULL REFERENCES products(id),
  frequency         TEXT NOT NULL CHECK (frequency IN ('DAILY','ALTERNATE','CUSTOM')),

-- in subscriptions table:
  daily_quantity    INTEGER,               -- used when frequency = DAILY
  daily_slot        TEXT DEFAULT 'MORNING' CHECK (daily_slot IN ('MORNING','EVENING')),
                                             -- Daily has no slot picker in the app (both shown disabled on
                                             -- that screen) — delivered every day on this single default slot.
  alternate_config  JSONB,                  -- { slots: ["EVENING"], startDateQuantity, succeedingDayQuantity }
  custom_config     JSONB,                  -- { slots: [...], selectedDays: ["MO","TU",...], quantityPerDay: {"MO":2,...} }

  start_date        DATE NOT NULL,
  end_date          DATE,                   -- null = runs until cancelled
  paused_ranges     JSONB NOT NULL DEFAULT '[]',  -- [{ startDate, endDate, reason }]
  skipped_dates     DATE[] NOT NULL DEFAULT '{}',

  status            TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','CANCELLED')),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_subscriptions_user ON subscriptions (user_id, status);

ALTER TABLE orders
  ADD CONSTRAINT fk_orders_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions(id);

-- ---------- Wallet (ledger-based — balance is always derived, never stored bare) ----------
CREATE TABLE wallet_transactions (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID NOT NULL REFERENCES users(id),
  type           TEXT NOT NULL CHECK (type IN ('TOPUP','ORDER_DEBIT','REFUND','CASHBACK')),
  amount         NUMERIC(10,2) NOT NULL,     -- negative for debits, positive for credits
  balance_after  NUMERIC(10,2) NOT NULL,
  reference_id   TEXT,
  status         TEXT NOT NULL DEFAULT 'SUCCESS' CHECK (status IN ('PENDING','SUCCESS','FAILED')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_wallet_txn_user ON wallet_transactions (user_id, created_at DESC);

ALTER TABLE orders
  ADD CONSTRAINT fk_orders_wallet_txn FOREIGN KEY (wallet_transaction_id) REFERENCES wallet_transactions(id);

-- ---------- Payment methods (gateway references only, never raw card/UPI data) ----------
CREATE TABLE payment_methods (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID NOT NULL REFERENCES users(id),
  type              TEXT NOT NULL CHECK (type IN ('UPI','CARD')),
  razorpay_token_id TEXT NOT NULL,
  display_label     TEXT NOT NULL,     -- "UPI •••• 4321"
  is_default        BOOLEAN NOT NULL DEFAULT false,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- Notifications ----------
CREATE TABLE notifications (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users(id),
  type          TEXT NOT NULL CHECK (type IN ('ORDER_CONFIRMED','ORDER_DELIVERED','SUBSCRIPTION_CREATED','WALLET_TOPUP','GENERAL')),
  title         TEXT NOT NULL,
  body          TEXT NOT NULL,
  read          BOOLEAN NOT NULL DEFAULT false,
  reference_id  TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_user ON notifications (user_id, created_at DESC);
